type Task {
  id: Int!
  parentId: Int
  slug: String!
  statusId: Int!
  tagsId: [Int!]!
  title: String!
  userId: Int!
}

type User {
  id: Int!
  fullName: String!
}

type Status {
  id: Int!
  name: String!
}

type Tag {
  id: Int!
  name: String!
  slug: String!
}

type Query {
  tasks: [Task!]!
  users: [User!]!
  statuses: [Status!]!
  tags: [Tag!]!
}

type Mutation {
  createTask(parentId: Int, title: String!, userId: Int!): Task!
  addTagForTask(taskId: Int!, tagName: String!): Task!
  removeTagFromTask(taskId: Int!, tagId: Int!): Task!
}
